repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Generate Helm chart README
        entry: helm-docs --chart-search-root charts/pixelfed
        language: system
        pass_filenames: false
