image:
  repo: "ghcr.io/grrywlsn/pixelfed-helm"
  tag: "v1.5.0"
createSecret: false
config:
  # Domain and session config
  # ADMIN_DOMAIN: Defaults to APP_DOMAIN
  # SESSION_DOMAIN: Defaults to APP_DOMAIN
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "86400"
  TRUST_PROXIES: "*"
  RESTRICTED_INSTANCE: "false"
  # Runtime config
  APP_ENV: "production"
  APP_DEBUG: "false"
  ENABLE_CONFIG_CACHE: "true"
  FORCE_HTTPS_URLS: "true"
  APP_TIMEZONE: "UTC"
  APP_LOCALE: "en"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"
  ADMIN_ENV_EDITOR: "true"
  # User experience config
  INSTANCE_DESCRIPTION: "Decentralized photo sharing social media powered by Pixelfed"
  INSTANCE_CONTACT_FORM: "true"
  OPEN_REGISTRATION: "true"
  ENFORCE_EMAIL_VERIFICATION: "true"
  OAUTH_ENABLED: "true"
  INSTANCE_DISCOVER_PUBLIC: "true"
  INSTANCE_PUBLIC_HASHTAGS: "true"
  STORIES_ENABLED: "true"
  INSTANCE_PROFILE_EMBEDS: "true"
  INSTANCE_POST_EMBEDS: "true"
  PF_HIDE_NSFW_ON_PUBLIC_FEEDS: "true"
  PF_ADMIN_INVITES_ENABLED: "true"
  INSTANCE_LANDING_SHOW_DIRECTORY: "true"
  INSTANCE_LANDING_SHOW_EXPLORE: "true"
  INSTANCE_SHOW_PEERS: "true"
  ACCOUNT_DELETION: "true"
  ACCOUNT_DELETE_AFTER: "false"
  PF_COSTAR_ENABLED: "false" # Costar content moderation
  # User experience config (Instagram import)
  PF_IMPORT_FROM_INSTAGRAM: "true"
  PF_IMPORT_IG_MAX_POSTS: "100"
  PF_IMPORT_IG_MAX_ATTEMPTS: "-1"
  PF_IMPORT_IG_ALLOW_VIDEO_POSTS: "true"
  PF_IMPORT_IG_PERM_ADMIN_ONLY: "false"
  PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY: "false"
  PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE: "0"
  PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT: "0"
  # User experience config (ActivityPub and federation)
  ACTIVITY_PUB: "true"
  AP_REMOTE_FOLLOW: "true"
  AP_SHAREDINBOX: "true"
  AP_INBOX: "true"
  AP_OUTBOX: "true"
  EXP_EMC: "true"
  ATOM_FEEDS: "true"
  NODEINFO: "true"
  WEBFINGER: "true"
  # User limits
  MAX_ACCOUNT_SIZE: "2000000"
  MAX_PHOTO_SIZE: "15000"
  MAX_AVATAR_SIZE: "2000"
  MAX_CAPTION_LENGTH: "500"
  MAX_BIO_LENGTH: "300"
  MAX_NAME_LENGTH: "30"
  MIN_PASSWORD_LENGTH: "8"
  MAX_ALBUM_LENGTH: "10"
  PF_MAX_USER_BLOCKS: "50"
  PF_MAX_USER_MUTES: "50"
  PF_MAX_DOMAIN_BLOCKS: "50"
  PF_MAX_COLLECTION_LENGTH: "100"
  LIMIT_ACCOUNT_SIZE: "true"
  BANNED_USERNAMES: ""
  RESTRICT_HTML_TYPES: "true"
  MAX_LINKS_PER_POST: "1"
  # S3 config
  PF_LOCAL_AVATAR_TO_CLOUD: "false"
  FILESYSTEM_DRIVER: "local"
  PF_ENABLE_CLOUD: "false"
  FILESYSTEM_CLOUD: "s3"
  MEDIA_DELETE_LOCAL_AFTER_CLOUD: "true"
  # Service capacity config
  PF_MAX_USERS: "2000"
  PF_ENFORCE_MAX_USERS: "true"
  # Media quality
  IMAGE_QUALITY: "95"
  PF_OPTIMIZE_IMAGES: "true"
  PF_OPTIMIZE_VIDEOS: "true"
  MEDIA_EXIF_DATABASE: "true"
  IMAGE_DRIVER: "imagick"
  # Horizon config
  HORIZON_PREFIX: "horizon-"
  HORIZON_DARKMODE: "false"
  HORIZON_MEMORY_LIMIT: "64"
  HORIZON_BALANCE_STRATEGY: "auto"
  HORIZON_MIN_PROCESSES: "1"
  HORIZON_MAX_PROCESSES: "20"
  HORIZON_SUPERVISOR_MEMORY: "64"
  HORIZON_SUPERVISOR_TRIES: "3"
  HORIZON_SUPERVISOR_NICE: "0"
  HORIZON_SUPERVISOR_TIMEOUT: "300"
  # PHP config
  PHP_MEMORY_LIMIT: "128M"
  PHP_ERROR_REPORTING: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  PHP_DISPLAY_ERRORS: "off"
  PHP_POST_MAX_SIZE: "100M"
  PHP_UPLOAD_MAX_FILESIZE: "100M"
  PHP_MAX_FILE_UPLOADS: "10"
  PHP_DATE_TIMEZONE: "UTC"
  PHP_OPCACHE_ENABLE: "1"
  PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
  PHP_OPCACHE_REVALIDATE_FREQ: "2"
