image:
  # -- repo to pull the Pixelfed image from
  repo: "ghcr.io/grrywlsn/pixelfed-helm"
  # -- version of the image to pull
  tag: "v2.0.1"
# -- The name of a secret to use instead of generating it from input values
existingSecret: ""
config:
  # -- The name for your Pixelfed server (how it appears in the UI) (REQUIRED)
  APP_NAME: ""
  # -- The URL of your Pixelfed server (e.g. pixelfed.example.com) - Do not include https:// (REQUIRED)
  APP_URL: ""
  # -- The email address for your Pixelfed admin/support address (REQUIRED)
  INSTANCE_CONTACT_EMAIL: ""
  domain:
    # -- The URL at which your Pixelfed server is accessible (e.g. https://pixelfed.example.com) - Must include https:// (REQUIRED)
    APP_DOMAIN: ""
    # -- The URL for the domain access; defaults to APP_DOMAIN
    ADMIN_DOMAIN: ""
    # -- The URL for the domain session; defaults to APP_DOMAIN
    SESSION_DOMAIN: ""
  network:
    # -- Proxies to trust, defaults to "*" to allow nginx-ingress or similar Kubernetes proxy
    TRUST_PROXIES: "*"
    # -- Redirects HTTP to HTTPS
    FORCE_HTTPS_URLS: "true"
  session:
    # -- The session driver to use to store user sessions
    SESSION_DRIVER: "database"
    # -- The lifetime of the session in seconds, defaults to 86400 (24 hours)
    SESSION_LIFETIME: "86400"
  runtime:
    # -- Tells Laravel and the Pixelfed server to use the production environment
    APP_ENV: "production"
    # -- Tells Laravel and the Pixelfed server to enable debugging mode
    APP_DEBUG: "false"
    # -- Tells Laravel and the Pixelfed server to cache config (this is recommended for production)
    ENABLE_CONFIG_CACHE: "true"
    # -- Default timezone to use for the server
    APP_TIMEZONE: "UTC"
    # -- Default locale to use for the server
    APP_LOCALE: "en"
    # -- How the server should log messages
    LOG_CHANNEL: "stack"
    # -- The default level of logging to use
    LOG_LEVEL: "debug"
    # -- Whether to use the env editor in the admin panel
    ADMIN_ENV_EDITOR: "false"
  server:
    # -- A description of your Pixelfed server
    INSTANCE_DESCRIPTION: "Decentralized photo sharing social media powered by Pixelfed"
    # -- If the contact form should be shown on the instance landing page
    INSTANCE_CONTACT_FORM: "true"
    # -- If your server is open for public signups
    OPEN_REGISTRATION: "true"
    # -- If your server is open for public signups but requires email verification
    RESTRICTED_INSTANCE: "false"
    # -- Enforces email verification for new accounts, before the account is activated
    ENFORCE_EMAIL_VERIFICATION: "true"
    # -- Enable oAuth support, required for mobile/3rd party apps
    OAUTH_ENABLED: "true"
    # -- Enable Curated Registration
    INSTANCE_CUR_REG: "false"
    # -- Enables public access to the Discover feature
    INSTANCE_DISCOVER_PUBLIC: "true"
    # -- Allow anonymous access to hashtag feeds
    INSTANCE_PUBLIC_HASHTAGS: "true"
    # -- Enable the Stories feature
    STORIES_ENABLED: "true"
    # -- Enable the profile embed feature
    INSTANCE_PROFILE_EMBEDS: "true"
    # -- Enable the post embed feature
    INSTANCE_POST_EMBEDS: "true"
    # -- Hide sensitive posts from public/network feeds
    PF_HIDE_NSFW_ON_PUBLIC_FEEDS: "true"
    # -- Enable the Admin Invites feature
    PF_ADMIN_INVITES_ENABLED: "true"
    # -- Enable the profile directory on the landing page
    INSTANCE_LANDING_SHOW_DIRECTORY: "true"
    # -- Enable the popular post explore on the landing page
    INSTANCE_LANDING_SHOW_EXPLORE: "true"
    # -- Enable the api/v1/peers API endpoint
    INSTANCE_SHOW_PEERS: "true"
    # -- Enable account deletion (may be a requirement in some jurisdictions)
    ACCOUNT_DELETION: "true"
    # -- Set to either a number of days after which to purge a deleted account, or "false" to delete immediately
    ACCOUNT_DELETE_AFTER: "false"
    # -- Enable the Costar feature
    PF_COSTAR_ENABLED: "false"
    # -- The max allowed account size in KB
    MAX_ACCOUNT_SIZE: "2000000"
    # -- The max photo/video size in KB	
    MAX_PHOTO_SIZE: "15000"
    # -- The max user avatar size in KB
    MAX_AVATAR_SIZE: "2000"
    # -- The max post caption length
    MAX_CAPTION_LENGTH: "500"
    # -- The max user bio length
    MAX_BIO_LENGTH: "300"
    # -- The max user display name length
    MAX_NAME_LENGTH: "30"
    # -- The min password length
    MIN_PASSWORD_LENGTH: "8"
    # -- The max number of media per post album
    MAX_ALBUM_LENGTH: "10"
    # -- The max number of user blocks per account
    PF_MAX_USER_BLOCKS: "50"
    # -- The max number of user mutes per account
    PF_MAX_USER_MUTES: "50"
    # -- The max number of domain blocks per account
    PF_MAX_DOMAIN_BLOCKS: "50"
    # -- Max collection post limit
    PF_MAX_COLLECTION_LENGTH: "100"
    # -- Whether to enforce the account size limits
    LIMIT_ACCOUNT_SIZE: "true"
    # -- Usernames to ban from registering
    BANNED_USERNAMES: ""
    # -- Prevent risky HTML types from being parsed in comments and other user
    RESTRICT_HTML_TYPES: "true"
    # -- Maximum number of URLs per post that will be rendered as a link
    MAX_LINKS_PER_POST: "1"
    # -- Limit max user registrations
    PF_MAX_USERS: "2000"
    # -- Whether to enforce the max user limit
    PF_ENFORCE_MAX_USERS: "true"
    instagram:
      # -- Whether to enable the Instagram import feature
      PF_IMPORT_FROM_INSTAGRAM: "true"
      # -- Maximum number of posts to import from Instagram
      PF_IMPORT_IG_MAX_POSTS: "100"
      # -- Maximum number of attempts to import from Instagram
      PF_IMPORT_IG_MAX_ATTEMPTS: "-1"
      # -- Whether to allow importing of videos from Instagram
      PF_IMPORT_IG_ALLOW_VIDEO_POSTS: "true"
      # -- Limit import to admin accounts only
      PF_IMPORT_IG_PERM_ADMIN_ONLY: "false"
      # -- Limit import to admin accounts and local accounts they follow only
      PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY: "false"
      # -- Limit to accounts older than X in days, or 0 for no limit
      PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE: "0"
      # -- Limit to accounts with a min follower count of X, or 0 for no limit
      PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT: "0"
  federation:
    # -- Whether to enable the ActivityPub federation feature
    ACTIVITY_PUB: "true"
    # -- Whether to enable the ActivityPub remote follow feature
    AP_REMOTE_FOLLOW: "true"
    # -- Whether to enable a shared inbox for remote follow requests
    AP_SHAREDINBOX: "true"
    # -- Whether to enable the ActivityPub inbox feature
    AP_INBOX: "true"
    # -- Whether to enable the ActivityPub outbox feature
    AP_OUTBOX: "true"
    # -- Enforce Mastoapi Compatibility (alpha)
    EXP_EMC: "true"
    # -- Whether to enable the ActivityPub atom feeds
    ATOM_FEEDS: "true"
    # -- Whether to enable the ActivityPub nodeinfo feature
    NODEINFO: "true"
    # -- Whether to enable the ActivityPub webfinger feature
    WEBFINGER: "true"
  database:
    # -- The database driver to use (e.g. mysql, pgsql) (REQUIRED)
    DB_CONNECTION: "pgsql"
    # -- The database name to use (REQUIRED)
    DB_DATABASE: "postgres"
    # -- The database host to connect to (e.g. localhost) (REQUIRED)
    DB_HOST: "localhost"
    # -- The database port to connect to (e.g. 3306, 5432) (REQUIRED)
    DB_PORT: "5432"
    # -- Enable database migrations on startup
    DB_APPLY_NEW_MIGRATIONS_AUTOMATICALLY: "true"
  redis:
    # -- Driver to use to broadcast events (e.g. redis, log, null)
    BROADCAST_DRIVER: "redis"
    # -- Driver to use to cache data (e.g. redis, file, database)
    CACHE_DRIVER: "redis"
    # -- Driver to use to store queues (e.g. redis, sqs, database)
    QUEUE_DRIVER: "redis"
    # -- Client to use for Redis (e.g. predis, phpredis)
    REDIS_CLIENT: "predis"
    # -- The Redis host to connect to (e.g. localhost)
    REDIS_HOST: "localhost"
    # -- The Redis port to connect to (e.g. 6379)
    REDIS_PORT: "6379"
    # -- The Redis prefix to use for keys
    REDIS_PREFIX: ""
    # -- The Redis scheme to use (e.g. tcp, unix)
    REDIS_SCHEME: "tcp"
  mail:
    # -- The mail driver to use (e.g. smtp, sendmail, mailgun)
    MAIL_DRIVER: "smtp"
    MAIL_ENCRYPTION: ""
    MAIL_FROM_ADDRESS: ""
    MAIL_FROM_NAME: ""
    MAIL_HOST: ""
    MAIL_PASSWORD: ""
    MAIL_PORT: ""
  storage:
    PF_LOCAL_AVATAR_TO_CLOUD: "false"
    FILESYSTEM_DRIVER: "local"
    PF_ENABLE_CLOUD: "false"
    FILESYSTEM_CLOUD: "s3"
    MEDIA_DELETE_LOCAL_AFTER_CLOUD: "true"
  aws:
    AWS_BUCKET: ""
    AWS_DEFAULT_REGION: ""
    AWS_ENDPOINT: ""
    AWS_URL: ""
    AWS_USE_PATH_STYLE_ENDPOINT: ""
    AWS_VISIBILITY: "public"
  media:
    IMAGE_QUALITY: "95"
    PF_OPTIMIZE_IMAGES: "true"
    PF_OPTIMIZE_VIDEOS: "true"
    MEDIA_EXIF_DATABASE: "true"
    IMAGE_DRIVER: "imagick"
  horizon:
    HORIZON_PREFIX: "horizon-"
    HORIZON_DARKMODE: "false"
    HORIZON_MEMORY_LIMIT: "64"
    HORIZON_BALANCE_STRATEGY: "auto"
    HORIZON_MIN_PROCESSES: "1"
    HORIZON_MAX_PROCESSES: "20"
    HORIZON_SUPERVISOR_MEMORY: "64"
    HORIZON_SUPERVISOR_TRIES: "10"
    HORIZON_SUPERVISOR_NICE: "0"
    HORIZON_SUPERVISOR_TIMEOUT: "300"
  php:
    PHP_MEMORY_LIMIT: "128M"
    PHP_ERROR_REPORTING: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
    PHP_DISPLAY_ERRORS: "off"
    PHP_POST_MAX_SIZE: "100M"
    PHP_UPLOAD_MAX_FILESIZE: "100M"
    PHP_MAX_FILE_UPLOADS: "10"
    PHP_DATE_TIMEZONE: "UTC"
    PHP_OPCACHE_ENABLE: "1"
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
    PHP_OPCACHE_REVALIDATE_FREQ: "2"
secret:
  # -- The secret key used to encrypt user sessions and other sensitive data (REQUIRED)
  APP_KEY: ""
  # -- The secret key used to authenticate the Pixelfed Pushgateway, for app notifications
  PIXELFED_PUSHGATEWAY_KEY: ""
  aws:
    # -- The AWS access key ID to use for S3 storage
    AWS_ACCESS_KEY_ID: ""
    # -- The AWS secret access key to use for S3 storage
    AWS_SECRET_ACCESS_KEY: ""
  database:
    # -- The database password to use (REQUIRED)
    DB_PASSWORD: ""
    # -- The database username to use (REQUIRED)
    DB_USERNAME: ""
  mail:
    # -- The mail username to use for SMTP
    MAIL_USERNAME: ""
    # -- The mail password to use for SMTP
    MAIL_PASSWORD: ""
  redis:
    # -- The Redis password to use
    REDIS_PASSWORD: ""
    # -- The Redis username to use
    REDIS_USERNAME: "redis"
redis:
  # -- Use the Redis subchart instead of relying on an external Redis server
  internal: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
