apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pixelfed.fullname" . | quote }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
data:
  ACCOUNT_DELETE_AFTER: {{ .Values.config.server.ACCOUNT_DELETE_AFTER | quote }}
  ACCOUNT_DELETION: {{ .Values.config.server.ACCOUNT_DELETION | quote }}
  ACTIVITY_PUB: {{ .Values.config.federation.ACTIVITY_PUB | quote }}
  ADMIN_DOMAIN: {{ default .Values.config.domain.APP_DOMAIN .Values.config.domain.ADMIN_DOMAIN | quote }}
  ADMIN_ENV_EDITOR: {{ .Values.config.runtime.ADMIN_ENV_EDITOR | quote }}
  AP_INBOX: {{ .Values.config.federation.AP_INBOX | quote }}
  AP_OUTBOX: {{ .Values.config.federation.AP_OUTBOX | quote }}
  AP_REMOTE_FOLLOW: {{ .Values.config.federation.AP_REMOTE_FOLLOW | quote }}
  AP_SHAREDINBOX: {{ .Values.config.federation.AP_SHAREDINBOX | quote }}
  APP_DEBUG: {{ .Values.config.runtime.APP_DEBUG | quote }}
  APP_DOMAIN: {{ required "config.domain.APP_DOMAIN is required but missing" .Values.config.domain.APP_DOMAIN | quote }}
  APP_ENV: {{ .Values.config.runtime.APP_ENV | quote }}
  APP_LOCALE: {{ .Values.config.runtime.APP_LOCALE | quote }}
  APP_NAME: {{ required "config.APP_NAME is required but missing" .Values.config.APP_NAME | quote }}
  APP_TIMEZONE: {{ .Values.config.runtime.APP_TIMEZONE | quote }}
  APP_URL: {{ required "config.APP_URL is required but missing" .Values.config.APP_URL | quote }}
  ATOM_FEEDS: {{ .Values.config.federation.ATOM_FEEDS | quote }}
  AWS_BUCKET: {{ .Values.config.aws.AWS_BUCKET | quote }}
  AWS_DEFAULT_REGION: {{ .Values.config.aws.AWS_DEFAULT_REGION | quote }}
  AWS_ENDPOINT: {{ .Values.config.aws.AWS_ENDPOINT | quote }}
  AWS_URL: {{ .Values.config.aws.AWS_URL | quote }}
  AWS_USE_PATH_STYLE_ENDPOINT: {{ .Values.config.aws.AWS_USE_PATH_STYLE_ENDPOINT | quote }}
  AWS_VISIBILITY: {{ .Values.config.aws.AWS_VISIBILITY | quote }}
  BANNED_USERNAMES: {{ .Values.config.server.BANNED_USERNAMES | quote }}
  BROADCAST_DRIVER: {{ .Values.config.redis.BROADCAST_DRIVER | quote }}
  CACHE_DRIVER: {{ .Values.config.redis.CACHE_DRIVER | quote }}
  DB_CONNECTION: {{ required "config.database.DB_CONNECTION is required but missing" .Values.config.database.DB_CONNECTION | quote }}
  DB_DATABASE: {{ required "config.database.DB_DATABASE is required but missing" .Values.config.database.DB_DATABASE | quote }}
  DB_HOST: {{ required "config.database.DB_HOST is required but missing" .Values.config.database.DB_HOST | quote }}
  DB_PORT: {{ required "config.database.DB_PORT is required but missing" .Values.config.database.DB_PORT | quote }}
  ENABLE_CONFIG_CACHE: {{ .Values.config.runtime.ENABLE_CONFIG_CACHE | quote }}
  ENFORCE_EMAIL_VERIFICATION: {{ .Values.config.server.ENFORCE_EMAIL_VERIFICATION | quote }}
  EXP_EMC: {{ .Values.config.federation.EXP_EMC | quote }}
  FILESYSTEM_CLOUD: {{ .Values.config.storage.FILESYSTEM_CLOUD | quote }}
  FILESYSTEM_DRIVER: {{ .Values.config.storage.FILESYSTEM_DRIVER | quote }}
  FORCE_HTTPS_URLS: {{ .Values.config.network.FORCE_HTTPS_URLS | quote }}
  HORIZON_BALANCE_STRATEGY: {{ .Values.config.horizon.HORIZON_BALANCE_STRATEGY | quote }}
  HORIZON_DARKMODE: {{ .Values.config.horizon.HORIZON_DARKMODE | quote }}
  HORIZON_MAX_PROCESSES: {{ .Values.config.horizon.HORIZON_MAX_PROCESSES | quote }}
  HORIZON_MEMORY_LIMIT: {{ .Values.config.horizon.HORIZON_MEMORY_LIMIT | quote }}
  HORIZON_MIN_PROCESSES: {{ .Values.config.horizon.HORIZON_MIN_PROCESSES | quote }}
  HORIZON_PREFIX: {{ .Values.config.horizon.HORIZON_PREFIX | quote }}
  HORIZON_SUPERVISOR_MEMORY: {{ .Values.config.horizon.HORIZON_SUPERVISOR_MEMORY | quote }}
  HORIZON_SUPERVISOR_NICE: {{ .Values.config.horizon.HORIZON_SUPERVISOR_NICE | quote }}
  HORIZON_SUPERVISOR_TIMEOUT: {{ .Values.config.horizon.HORIZON_SUPERVISOR_TIMEOUT | quote }}
  HORIZON_SUPERVISOR_TRIES: {{ .Values.config.horizon.HORIZON_SUPERVISOR_TRIES | quote }}
  IMAGE_DRIVER: {{ .Values.config.media.IMAGE_DRIVER | quote }}
  IMAGE_QUALITY: {{ .Values.config.media.IMAGE_QUALITY | quote }}
  INSTANCE_CONTACT_EMAIL: {{ required "config.INSTANCE_CONTACT_EMAIL is required but missing" .Values.config.INSTANCE_CONTACT_EMAIL | quote }}
  INSTANCE_CUR_REG: {{ .Values.config.server.INSTANCE_CUR_REG | quote }}
  INSTANCE_CONTACT_FORM: {{ .Values.config.server.INSTANCE_CONTACT_FORM | quote }}
  INSTANCE_DESCRIPTION: {{ .Values.config.server.INSTANCE_DESCRIPTION | quote }}
  INSTANCE_DISCOVER_PUBLIC: {{ .Values.config.server.INSTANCE_DISCOVER_PUBLIC | quote }}
  INSTANCE_LANDING_SHOW_DIRECTORY: {{ .Values.config.server.INSTANCE_LANDING_SHOW_DIRECTORY | quote }}
  INSTANCE_LANDING_SHOW_EXPLORE: {{ .Values.config.server.INSTANCE_LANDING_SHOW_EXPLORE | quote }}
  INSTANCE_POST_EMBEDS: {{ .Values.config.server.INSTANCE_POST_EMBEDS | quote }}
  INSTANCE_PROFILE_EMBEDS: {{ .Values.config.server.INSTANCE_PROFILE_EMBEDS | quote }}
  INSTANCE_PUBLIC_HASHTAGS: {{ .Values.config.server.INSTANCE_PUBLIC_HASHTAGS | quote }}
  INSTANCE_SHOW_PEERS: {{ .Values.config.server.INSTANCE_SHOW_PEERS | quote }}
  LIMIT_ACCOUNT_SIZE: {{ .Values.config.server.LIMIT_ACCOUNT_SIZE | quote }}
  LOG_CHANNEL: {{ .Values.config.runtime.LOG_CHANNEL | quote }}
  LOG_LEVEL: {{ .Values.config.runtime.LOG_LEVEL | quote }}
  MAIL_DRIVER: {{ .Values.config.mail.MAIL_DRIVER | quote }}
  MAX_ACCOUNT_SIZE: {{ .Values.config.server.MAX_ACCOUNT_SIZE | quote }}
  MAX_ALBUM_LENGTH: {{ .Values.config.server.MAX_ALBUM_LENGTH | quote }}
  MAX_AVATAR_SIZE: {{ .Values.config.server.MAX_AVATAR_SIZE | quote }}
  MAX_BIO_LENGTH: {{ .Values.config.server.MAX_BIO_LENGTH | quote }}
  MAX_CAPTION_LENGTH: {{ .Values.config.server.MAX_CAPTION_LENGTH | quote }}
  MAX_LINKS_PER_POST: {{ .Values.config.server.MAX_LINKS_PER_POST | quote }}
  MAX_NAME_LENGTH: {{ .Values.config.server.MAX_NAME_LENGTH | quote }}
  MAX_PHOTO_SIZE: {{ .Values.config.server.MAX_PHOTO_SIZE | quote }}
  MEDIA_DELETE_LOCAL_AFTER_CLOUD: {{ .Values.config.storage.MEDIA_DELETE_LOCAL_AFTER_CLOUD | quote }}
  MEDIA_EXIF_DATABASE: {{ .Values.config.media.MEDIA_EXIF_DATABASE | quote }}
  MIN_PASSWORD_LENGTH: {{ .Values.config.server.MIN_PASSWORD_LENGTH | quote }}
  NODEINFO: {{ .Values.config.federation.NODEINFO | quote }}
  OAUTH_ENABLED: {{ .Values.config.server.OAUTH_ENABLED | quote }}
  OPEN_REGISTRATION: {{ .Values.config.server.OPEN_REGISTRATION | quote }}
  PF_ADMIN_INVITES_ENABLED: {{ .Values.config.server.PF_ADMIN_INVITES_ENABLED | quote }}
  PF_COSTAR_ENABLED: {{ .Values.config.server.PF_COSTAR_ENABLED | quote }}
  PF_ENABLE_CLOUD: {{ .Values.config.storage.PF_ENABLE_CLOUD | quote }}
  PF_ENFORCE_MAX_USERS: {{ .Values.config.server.PF_ENFORCE_MAX_USERS | quote }}
  PF_HIDE_NSFW_ON_PUBLIC_FEEDS: {{ .Values.config.server.PF_HIDE_NSFW_ON_PUBLIC_FEEDS | quote }}
  PF_IMPORT_FROM_INSTAGRAM: {{ .Values.config.server.instagram.PF_IMPORT_FROM_INSTAGRAM | quote }}
  PF_IMPORT_IG_ALLOW_VIDEO_POSTS: {{ .Values.config.server.instagram.PF_IMPORT_IG_ALLOW_VIDEO_POSTS | quote }}
  PF_IMPORT_IG_MAX_ATTEMPTS: {{ .Values.config.server.instagram.PF_IMPORT_IG_MAX_ATTEMPTS | quote }}
  PF_IMPORT_IG_MAX_POSTS: {{ .Values.config.server.instagram.PF_IMPORT_IG_MAX_POSTS | quote }}
  PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY: {{ .Values.config.server.instagram.PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY | quote }}
  PF_IMPORT_IG_PERM_ADMIN_ONLY: {{ .Values.config.server.instagram.PF_IMPORT_IG_PERM_ADMIN_ONLY | quote }}
  PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE: {{ .Values.config.server.instagram.PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE | quote }}
  PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT: {{ .Values.config.server.instagram.PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT | quote }}
  PF_LOCAL_AVATAR_TO_CLOUD: {{ .Values.config.storage.PF_LOCAL_AVATAR_TO_CLOUD | quote }}
  PF_MAX_COLLECTION_LENGTH: {{ .Values.config.server.PF_MAX_COLLECTION_LENGTH | quote }}
  PF_MAX_DOMAIN_BLOCKS: {{ .Values.config.server.PF_MAX_DOMAIN_BLOCKS | quote }}
  PF_MAX_USER_BLOCKS: {{ .Values.config.server.PF_MAX_USER_BLOCKS | quote }}
  PF_MAX_USER_MUTES: {{ .Values.config.server.PF_MAX_USER_MUTES | quote }}
  PF_MAX_USERS: {{ .Values.config.server.PF_MAX_USERS | quote }}
  PF_OPTIMIZE_IMAGES: {{ .Values.config.media.PF_OPTIMIZE_IMAGES | quote }}
  PF_OPTIMIZE_VIDEOS: {{ .Values.config.media.PF_OPTIMIZE_VIDEOS | quote }}
  PHP_DATE_TIMEZONE: {{ .Values.config.php.PHP_DATE_TIMEZONE | quote }}
  PHP_DISPLAY_ERRORS: {{ .Values.config.php.PHP_DISPLAY_ERRORS | quote }}
  PHP_ERROR_REPORTING: {{ .Values.config.php.PHP_ERROR_REPORTING | quote }}
  PHP_MAX_FILE_UPLOADS: {{ .Values.config.php.PHP_MAX_FILE_UPLOADS | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.config.php.PHP_MEMORY_LIMIT | quote }}
  PHP_OPCACHE_ENABLE: {{ .Values.config.php.PHP_OPCACHE_ENABLE | quote }}
  PHP_OPCACHE_REVALIDATE_FREQ: {{ .Values.config.php.PHP_OPCACHE_REVALIDATE_FREQ | quote }}
  PHP_OPCACHE_VALIDATE_TIMESTAMPS: {{ .Values.config.php.PHP_OPCACHE_VALIDATE_TIMESTAMPS | quote }}
  PHP_POST_MAX_SIZE: {{ .Values.config.php.PHP_POST_MAX_SIZE | quote }}
  PHP_UPLOAD_MAX_FILESIZE: {{ .Values.config.php.PHP_UPLOAD_MAX_FILESIZE | quote }}
  QUEUE_DRIVER: {{ .Values.config.redis.QUEUE_DRIVER | quote }}
  REDIS_CLIENT: {{ .Values.config.redis.REDIS_CLIENT | quote }}
  REDIS_HOST: {{ .Values.config.redis.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.redis.REDIS_PORT | quote }}
  REDIS_PREFIX: {{ .Values.config.redis.REDIS_PREFIX | quote }}
  REDIS_SCHEME: {{ .Values.config.redis.REDIS_SCHEME | quote }}
  RESTRICT_HTML_TYPES: {{ .Values.config.server.RESTRICT_HTML_TYPES | quote }}
  RESTRICTED_INSTANCE: {{ .Values.config.server.RESTRICTED_INSTANCE | quote }}
  SESSION_DOMAIN: {{ default .Values.config.domain.APP_DOMAIN .Values.config.domain.SESSION_DOMAIN | quote }}
  SESSION_DRIVER: {{ .Values.config.session.SESSION_DRIVER | quote }}
  SESSION_LIFETIME: {{ .Values.config.session.SESSION_LIFETIME | quote }}
  STORIES_ENABLED: {{ .Values.config.server.STORIES_ENABLED | quote }}
  TRUST_PROXIES: {{ .Values.config.network.TRUST_PROXIES | quote }}
  WEBFINGER: {{ .Values.config.federation.WEBFINGER | quote }}
