apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pixelfed.fullname" . | quote }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
data:
  ACCOUNT_DELETE_AFTER: {{ .Values.config.ACCOUNT_DELETE_AFTER | quote }}
  ACCOUNT_DELETION: {{ .Values.config.ACCOUNT_DELETION | quote }}
  ACTIVITY_PUB: {{ .Values.config.ACTIVITY_PUB | quote }}
  ADMIN_DOMAIN: {{ default .Values.config.APP_DOMAIN .Values.config.ADMIN_DOMAIN | quote }}
  ADMIN_ENV_EDITOR: {{ .Values.config.ADMIN_ENV_EDITOR | quote }}
  AP_INBOX: {{ .Values.config.AP_INBOX | quote }}
  AP_OUTBOX: {{ .Values.config.AP_OUTBOX | quote }}
  AP_REMOTE_FOLLOW: {{ .Values.config.AP_REMOTE_FOLLOW | quote }}
  AP_SHAREDINBOX: {{ .Values.config.AP_SHAREDINBOX | quote }}
  APP_DEBUG: {{ .Values.config.APP_DEBUG | quote }}
  APP_DOMAIN: {{ required "config.APP_DOMAIN is required but missing" .Values.config.APP_DOMAIN | quote }}
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_LOCALE: {{ .Values.config.APP_LOCALE | quote }}
  APP_NAME: {{ required "config.APP_NAME is required but missing" .Values.config.APP_NAME | quote }}
  APP_TIMEZONE: {{ .Values.config.APP_TIMEZONE | quote }}
  APP_URL: {{ required "config.APP_URL is required but missing" .Values.config.APP_URL | quote }}
  ATOM_FEEDS: {{ .Values.config.ATOM_FEEDS | quote }}
  BANNED_USERNAMES: {{ .Values.config.BANNED_USERNAMES | quote }}
  BROADCAST_DRIVER: {{ .Values.config.BROADCAST_DRIVER | quote }}
  CACHE_DRIVER: {{ .Values.config.CACHE_DRIVER | quote }}
  ENABLE_CONFIG_CACHE: {{ .Values.config.ENABLE_CONFIG_CACHE | quote }}
  ENFORCE_EMAIL_VERIFICATION: {{ .Values.config.ENFORCE_EMAIL_VERIFICATION | quote }}
  EXP_EMC: {{ .Values.config.EXP_EMC | quote }}
  FILESYSTEM_CLOUD: {{ .Values.config.FILESYSTEM_CLOUD | quote }}
  FILESYSTEM_DRIVER: {{ .Values.config.FILESYSTEM_DRIVER | quote }}
  FORCE_HTTPS_URLS: {{ .Values.config.FORCE_HTTPS_URLS | quote }}
  HORIZON_BALANCE_STRATEGY: {{ .Values.config.HORIZON_BALANCE_STRATEGY | quote }}
  HORIZON_DARKMODE: {{ .Values.config.HORIZON_DARKMODE | quote }}
  HORIZON_MAX_PROCESSES: {{ .Values.config.HORIZON_MAX_PROCESSES | quote }}
  HORIZON_MEMORY_LIMIT: {{ .Values.config.HORIZON_MEMORY_LIMIT | quote }}
  HORIZON_MIN_PROCESSES: {{ .Values.config.HORIZON_MIN_PROCESSES | quote }}
  HORIZON_PREFIX: {{ .Values.config.HORIZON_PREFIX | quote }}
  HORIZON_SUPERVISOR_MEMORY: {{ .Values.config.HORIZON_SUPERVISOR_MEMORY | quote }}
  HORIZON_SUPERVISOR_NICE: {{ .Values.config.HORIZON_SUPERVISOR_NICE | quote }}
  HORIZON_SUPERVISOR_TIMEOUT: {{ .Values.config.HORIZON_SUPERVISOR_TIMEOUT | quote }}
  HORIZON_SUPERVISOR_TRIES: {{ .Values.config.HORIZON_SUPERVISOR_TRIES | quote }}
  IMAGE_DRIVER: {{ .Values.config.IMAGE_DRIVER | quote }}
  IMAGE_QUALITY: {{ .Values.config.IMAGE_QUALITY | quote }}
  INSTANCE_CONTACT_EMAIL: {{ required "config.INSTANCE_CONTACT_EMAIL is required but missing" .Values.config.INSTANCE_CONTACT_EMAIL | quote }}
  INSTANCE_CONTACT_FORM: {{ .Values.config.INSTANCE_CONTACT_FORM | quote }}
  INSTANCE_DESCRIPTION: {{ .Values.config.INSTANCE_DESCRIPTION | quote }}
  INSTANCE_DISCOVER_PUBLIC: {{ .Values.config.INSTANCE_DISCOVER_PUBLIC | quote }}
  INSTANCE_LANDING_SHOW_DIRECTORY: {{ .Values.config.INSTANCE_LANDING_SHOW_DIRECTORY | quote }}
  INSTANCE_LANDING_SHOW_EXPLORE: {{ .Values.config.INSTANCE_LANDING_SHOW_EXPLORE | quote }}
  INSTANCE_POST_EMBEDS: {{ .Values.config.INSTANCE_POST_EMBEDS | quote }}
  INSTANCE_PROFILE_EMBEDS: {{ .Values.config.INSTANCE_PROFILE_EMBEDS | quote }}
  INSTANCE_PUBLIC_HASHTAGS: {{ .Values.config.INSTANCE_PUBLIC_HASHTAGS | quote }}
  INSTANCE_SHOW_PEERS: {{ .Values.config.INSTANCE_SHOW_PEERS | quote }}
  LIMIT_ACCOUNT_SIZE: {{ .Values.config.LIMIT_ACCOUNT_SIZE | quote }}
  LOG_CHANNEL: {{ .Values.config.LOG_CHANNEL | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  MAX_ACCOUNT_SIZE: {{ .Values.config.MAX_ACCOUNT_SIZE | quote }}
  MAX_ALBUM_LENGTH: {{ .Values.config.MAX_ALBUM_LENGTH | quote }}
  MAX_AVATAR_SIZE: {{ .Values.config.MAX_AVATAR_SIZE | quote }}
  MAX_BIO_LENGTH: {{ .Values.config.MAX_BIO_LENGTH | quote }}
  MAX_CAPTION_LENGTH: {{ .Values.config.MAX_CAPTION_LENGTH | quote }}
  MAX_LINKS_PER_POST: {{ .Values.config.MAX_LINKS_PER_POST | quote }}
  MAX_NAME_LENGTH: {{ .Values.config.MAX_NAME_LENGTH | quote }}
  MAX_PHOTO_SIZE: {{ .Values.config.MAX_PHOTO_SIZE | quote }}
  MEDIA_DELETE_LOCAL_AFTER_CLOUD: {{ .Values.config.MEDIA_DELETE_LOCAL_AFTER_CLOUD | quote }}
  MEDIA_EXIF_DATABASE: {{ .Values.config.MEDIA_EXIF_DATABASE | quote }}
  MIN_PASSWORD_LENGTH: {{ .Values.config.MIN_PASSWORD_LENGTH | quote }}
  NODEINFO: {{ .Values.config.NODEINFO | quote }}
  OAUTH_ENABLED: {{ .Values.config.OAUTH_ENABLED | quote }}
  OPEN_REGISTRATION: {{ .Values.config.OPEN_REGISTRATION | quote }}
  PF_ADMIN_INVITES_ENABLED: {{ .Values.config.PF_ADMIN_INVITES_ENABLED | quote }}
  PF_COSTAR_ENABLED: {{ .Values.config.PF_COSTAR_ENABLED | quote }}
  PF_ENABLE_CLOUD: {{ .Values.config.PF_ENABLE_CLOUD | quote }}
  PF_ENFORCE_MAX_USERS: {{ .Values.config.PF_ENFORCE_MAX_USERS | quote }}
  PF_HIDE_NSFW_ON_PUBLIC_FEEDS: {{ .Values.config.PF_HIDE_NSFW_ON_PUBLIC_FEEDS | quote }}
  PF_IMPORT_FROM_INSTAGRAM: {{ .Values.config.PF_IMPORT_FROM_INSTAGRAM | quote }}
  PF_IMPORT_IG_ALLOW_VIDEO_POSTS: {{ .Values.config.PF_IMPORT_IG_ALLOW_VIDEO_POSTS | quote }}
  PF_IMPORT_IG_MAX_ATTEMPTS: {{ .Values.config.PF_IMPORT_IG_MAX_ATTEMPTS | quote }}
  PF_IMPORT_IG_MAX_POSTS: {{ .Values.config.PF_IMPORT_IG_MAX_POSTS | quote }}
  PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY: {{ .Values.config.PF_IMPORT_IG_PERM_ADMIN_FOLLOWS_ONLY | quote }}
  PF_IMPORT_IG_PERM_ADMIN_ONLY: {{ .Values.config.PF_IMPORT_IG_PERM_ADMIN_ONLY | quote }}
  PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE: {{ .Values.config.PF_IMPORT_IG_PERM_MIN_ACCOUNT_AGE | quote }}
  PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT: {{ .Values.config.PF_IMPORT_IG_PERM_MIN_FOLLOWER_COUNT | quote }}
  PF_LOCAL_AVATAR_TO_CLOUD: {{ .Values.config.PF_LOCAL_AVATAR_TO_CLOUD | quote }}
  PF_MAX_COLLECTION_LENGTH: {{ .Values.config.PF_MAX_COLLECTION_LENGTH | quote }}
  PF_MAX_DOMAIN_BLOCKS: {{ .Values.config.PF_MAX_DOMAIN_BLOCKS | quote }}
  PF_MAX_USER_BLOCKS: {{ .Values.config.PF_MAX_USER_BLOCKS | quote }}
  PF_MAX_USER_MUTES: {{ .Values.config.PF_MAX_USER_MUTES | quote }}
  PF_MAX_USERS: {{ .Values.config.PF_MAX_USERS | quote }}
  PF_OPTIMIZE_IMAGES: {{ .Values.config.PF_OPTIMIZE_IMAGES | quote }}
  PF_OPTIMIZE_VIDEOS: {{ .Values.config.PF_OPTIMIZE_VIDEOS | quote }}
  PHP_DATE_TIMEZONE: {{ .Values.config.PHP_DATE_TIMEZONE | quote }}
  PHP_DISPLAY_ERRORS: {{ .Values.config.PHP_DISPLAY_ERRORS | quote }}
  PHP_ERROR_REPORTING: {{ .Values.config.PHP_ERROR_REPORTING | quote }}
  PHP_MAX_FILE_UPLOADS: {{ .Values.config.PHP_MAX_FILE_UPLOADS | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.config.PHP_MEMORY_LIMIT | quote }}
  PHP_OPCACHE_ENABLE: {{ .Values.config.PHP_OPCACHE_ENABLE | quote }}
  PHP_OPCACHE_REVALIDATE_FREQ: {{ .Values.config.PHP_OPCACHE_REVALIDATE_FREQ | quote }}
  PHP_OPCACHE_VALIDATE_TIMESTAMPS: {{ .Values.config.PHP_OPCACHE_VALIDATE_TIMESTAMPS | quote }}
  PHP_POST_MAX_SIZE: {{ .Values.config.PHP_POST_MAX_SIZE | quote }}
  PHP_UPLOAD_MAX_FILESIZE: {{ .Values.config.PHP_UPLOAD_MAX_FILESIZE | quote }}
  QUEUE_DRIVER: {{ .Values.config.QUEUE_DRIVER | quote }}
  RESTRICT_HTML_TYPES: {{ .Values.config.RESTRICT_HTML_TYPES | quote }}
  RESTRICTED_INSTANCE: {{ .Values.config.RESTRICTED_INSTANCE | quote }}
  SESSION_DOMAIN: {{ default .Values.config.APP_DOMAIN .Values.config.SESSION_DOMAIN | quote }}
  SESSION_DRIVER: {{ .Values.config.SESSION_DRIVER | quote }}
  SESSION_LIFETIME: {{ .Values.config.SESSION_LIFETIME | quote }}
  STORIES_ENABLED: {{ .Values.config.STORIES_ENABLED | quote }}
  TRUST_PROXIES: {{ .Values.config.TRUST_PROXIES | quote }}
  WEBFINGER: {{ .Values.config.WEBFINGER | quote }}