apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pixelfed.fullname" . }}
  labels:
    app: {{ include "pixelfed.fullname" . }}
spec:
  minReadySeconds: 1
  progressDeadlineSeconds: 120
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ include "pixelfed.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "pixelfed.fullname" . }}
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: "{{ include "pixelfed.fullname" . }}"
            - secretRef:
                name: "{{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ include "pixelfed.fullname" . }}{{ end }}"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 150
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 4
          readinessProbe:
            failureThreshold: 4
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 4
          resources:
            requests:
              memory: {{ .Values.resources.memory.request | default "2Gi" }}
            limits:
              memory: {{ .Values.resources.memory.limit | default "2Gi" }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: upload-folder
              mountPath: /var/www/html/storage/app/public
        - name: worker
          envFrom:
            - configMapRef:
                name: "{{ include "pixelfed.fullname" . }}"
            - secretRef:
                name: "{{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ include "pixelfed.fullname" . }}{{ end }}"
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          workingDir: /var/www/html
          command: ["php"]
          args: ["artisan", "horizon"]
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: upload-folder
              mountPath: /var/www/html/storage/app/public
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
        - name: upload-folder
          persistentVolumeClaim:
            claimName: {{ include "pixelfed.fullname" . }}
