{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pixelfed.fullname" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
data:
  APP_KEY: {{ required "secret.APP_KEY is required but missing" .Values.secret.APP_KEY | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.aws.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.aws.AWS_SECRET_ACCESS_KEY | b64enc }}
  DB_PASSWORD: {{  required "secret.database.DB_PASSWORD is required but missing" .Values.secret.database.DB_PASSWORD | b64enc }}
  DB_USERNAME: {{ required "secret.database.DB_USERNAME is required but missing" .Values.secret.database.DB_USERNAME | b64enc }}
  MAIL_PASSWORD: {{ .Values.secret.mail.MAIL_PASSWORD | b64enc }}
  MAIL_USERNAME: {{ .Values.secret.mail.MAIL_USERNAME | b64enc }}
  PIXELFED_PUSHGATEWAY_KEY: {{ .Values.secret.PIXELFED_PUSHGATEWAY_KEY | b64enc }}
  REDIS_PASSWORD: {{ .Values.secret.redis.REDIS_PASSWORD | b64enc }}
  REDIS_USERNAME: {{ .Values.secret.redis.REDIS_USERNAME | b64enc }}
{{- end }}