{{- if and .Values.createSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pixelfed.fullname" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
data:
  APP_KEY: {{ required "config.APP_KEY is required but missing" .Values.config.APP_KEY }}
  AWS_ACCESS_KEY_ID: {{ .Values.config.AWS_ACCESS_KEY_ID | quote }}
  AWS_BUCKET: {{ .Values.config.AWS_BUCKET | quote }}
  AWS_DEFAULT_REGION: {{ .Values.config.AWS_DEFAULT_REGION | quote }}
  AWS_ENDPOINT: {{ .Values.config.AWS_ENDPOINT | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_URL: {{ .Values.config.AWS_URL | quote }}
  AWS_USE_PATH_STYLE_ENDPOINT: {{ .Values.config.AWS_USE_PATH_STYLE_ENDPOINT | quote }}
  AWS_VISIBILITY: {{ .Values.config.AWS_VISIBILITY | quote }}
  DB_CONNECTION: {{ required "config.DB_CONNECTION is required but missing" .Values.config.DB_CONNECTION | quote }}
  DB_DATABASE: {{ required "config.DB_DATABASE is required but missing" .Values.config.DB_DATABASE | quote }}
  DB_HOST: {{ required "config.DB_HOST is required but missing" .Values.config.DB_HOST | quote }}
  DB_PASSWORD: {{  required "config.DB_PASSWORD is required but missing" .Values.config.DB_PASSWORD | quote }}
  DB_PORT: {{ required "config.DB_PORT is required but missing" .Values.config.DB_PORT | quote }}
  DB_USERNAME: {{ required "config.DB_USERNAME is required but missing" .Values.config.DB_USERNAME | quote }}
  MAIL_DRIVER: {{ .Values.config.MAIL_DRIVER | quote }}
  MAIL_ENCRYPTION: {{ .Values.config.MAIL_ENCRYPTION | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.config.MAIL_FROM_ADDRESS | quote }}
  MAIL_FROM_NAME: {{ .Values.config.MAIL_FROM_NAME | quote }}
  MAIL_HOST: {{ .Values.config.MAIL_HOST | quote }}
  MAIL_PASSWORD: {{ .Values.config.MAIL_PASSWORD | quote }}
  MAIL_PORT: {{ .Values.config.MAIL_PORT | quote }}
  MAIL_USERNAME: {{ .Values.config.MAIL_USERNAME | quote }}
  PIXELFED_PUSHGATEWAY_KEY: {{ .Values.config.PIXELFED_PUSHGATEWAY_KEY }}
  REDIS_CLIENT: {{ .Values.config.REDIS_CLIENT | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PASSWORD: {{ .Values.config.REDIS_PASSWORD | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}
  REDIS_PREFIX: {{ .Values.config.REDIS_PREFIX | quote }}
  REDIS_SCHEME: {{ .Values.config.REDIS_SCHEME | quote }}
  REDIS_USERNAME: {{ .Values.config.REDIS_USERNAME | quote }}
{{- end }}