name: Tag, Build and upload post-merge
on:
  pull_request:
    types: [closed]

env:
  VERSION_TAG: 0.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      discussions: 'write'
      packages: 'write'
      id-token: 'write'

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: "${{ env.VERSION_TAG }}"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: 'Get next version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    # Major version
    - uses: softprops/action-gh-release@v1
      if: contains(github.event.pull_request.labels.*.name, 'major')
      with:
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "${{ steps.semvers.outputs.v_major }}"

    - id: set-version-env-major
      if: contains(github.event.pull_request.labels.*.name, 'major')
      run: |
        echo "VERSION_TAG=${{ steps.semvers.outputs.v_major }}" >> $GITHUB_ENV

    # Minor version
    - uses: softprops/action-gh-release@v1
      if: contains(github.event.pull_request.labels.*.name, 'minor')
      with:
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "${{ steps.semvers.outputs.v_minor }}"

    - id: set-version-env-minor
      if: contains(github.event.pull_request.labels.*.name, 'minor')
      run: |
        echo "VERSION_TAG=${{ steps.semvers.outputs.v_minor }}" >> $GITHUB_ENV

    # Patch version
    - uses: softprops/action-gh-release@v1
      if: contains(github.event.pull_request.labels.*.name, 'patch')
      with:
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "${{ steps.semvers.outputs.v_patch }}"

    - id: set-version-env-patch
      if: contains(github.event.pull_request.labels.*.name, 'patch')
      run: |
        echo "VERSION_TAG=${{ steps.semvers.outputs.v_patch }}" >> $GITHUB_ENV

    - name: Set version tag
      id: set-version-tag
      run: |
        echo "Version tag is ${VERSION_TAG}"
        echo "version-tag=${VERSION_TAG}" >> $GITHUB_OUTPUT

    - uses: softprops/action-gh-release@v1
      name: "Tag release"
      with:
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "${{ steps.set-version-tag.outputs.version-tag }}"

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        load: true
        tags: ghcr.io/grrywlsn/pixelfed-helm:${{ steps.set-version-tag.outputs.version-tag }}

    - name: Push docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/grrywlsn/pixelfed-helm:${{ steps.set-version-tag.outputs.version-tag }}

    - name: Update helm chart version
      if: github.ref == 'refs/heads/main'
      run: |
        sed -i "s/^version:.*/version: ${{ steps.set-version-tag.outputs.version-tag }}/" charts/pixelfed/Chart.yaml

    - name: Update image tag in values.yaml
      if: github.ref == 'refs/heads/main'
      run: |
        sed -i 's/^  tag: .*/  tag: "${{ steps.set-version-tag.outputs.version-tag }}"/' charts/pixelfed/values.yaml

    - name: Configure Git
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run chart-releaser
      if: github.ref == 'refs/heads/main'
      uses: helm/chart-releaser-action@v1.7.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Set up SSH Key
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and push changes
      if: github.ref == 'refs/heads/main'
      run: |
        git add charts/pixelfed/Chart.yaml charts/pixelfed/values.yaml
        git commit -m "Update helm chart version and image tag to ${{ steps.set-version-tag.outputs.version-tag }}"
        git push git@github.com:grrywlsn/pixelfed-helm.git main